import type {
  EventDetail,
  EventSummary,
  Health,
  Portfolio,
  Run,
  Scenario,
  Signal,
  Source,
} from "../types";
export const signal: Signal = {
  id: "signal1",
  event_id: "event1",
  source_record_id: "source1",
  event_class: "Macroeconomic",
  event_subtype: "rate_hike",
  assertion_status: "asserted",
  impact_score: 8,
  impact_components: {
    magnitude_points: 4,
    scope_points: 3,
    rationale: "50 bp policy move, US scope.",
    rubric_version: "severity_v1",
  },
  sentiment_score: 0.744,
  sentiment_model_id: "ProsusAI/finbert",
  model_revision: "pinned-test-revision",
  sentiment_probabilities: { positive: 0.8, negative: 0.056, neutral: 0.144 },
  engine_version: "rules1-finbert1",
  created_at: "2026-10-05T00:00:00Z",
  simulation_clock: "2026-10-05T00:00:00Z",
  review_reasons: [],
  evidence_spans: [{ start: 20, end: 42, text: "raised its policy rate" }],
  affected_issuers: [],
  affected_sectors: [],
  affected_regions: ["US"],
};
export const source: Source = {
  id: "source1",
  publisher: "Fictional scenario feed",
  source_family: "synthetic",
  source_id: "sample_news",
  canonical_uri: "synthetic://policy/hike",
  text: "The Federal Reserve raised its policy rate by 50 basis points.",
  text_kind: "supplied_text",
  published_at: "2026-10-04T12:00:00Z",
  retrieved_at: "2026-10-05T00:00:00Z",
  provenance_mode: "synthetic",
  verified_publisher: false,
};
export const event: EventSummary = {
  id: "event1",
  primary_signal: signal,
  source_record_ids: ["source1"],
  source_families: ["synthetic"],
  provenance_modes: ["synthetic"],
  verified_publisher_count: 0,
  evidence_independent: false,
  eligibility: {
    state: "eligible_simulation",
    scenario_id: "monetary_tightening",
    reasons: [],
    rate_position_ids: ["L01"],
    spread_position_ids: [],
    reference_clock: "2026-10-05T00:00:00Z",
    evaluated_at: "2026-10-05T00:00:00Z",
  },
};
export const detail: EventDetail = {
  event,
  evidence: [source],
  signals: [signal],
  eligibility: event.eligibility!,
  stress_run_ids: ["run1"],
};
export const portfolio: Portfolio = {
  name: "Fictional USD wholesale banking portfolio",
  version: "test-portfolio",
  currency: "USD",
  provenance: "synthetic",
  base_total_usd: "1000000.00",
  notional_total_usd: "1100000.00",
  assumptions: [
    "All positions are fictional.",
    "First-order approximation; no convexity.",
  ],
  positions: [
    {
      id: "L01",
      issuer: "Aster Energy",
      asset_type: "loan",
      instrument_type: "fixed",
      sector: "energy",
      region: "US",
      currency: "USD",
      base_market_value_usd: "1000000.00",
      notional_usd: "1100000.00",
      rate_duration: "4",
      spread_duration: "3",
      signed_rate_pnl_per_bp: "0",
    },
  ],
};
export const scenarios: Scenario[] = [
  {
    id: "monetary_tightening",
    version: "stress-v1",
    name: "Monetary tightening",
    event_subtype: "rate_hike",
    reference_impact: 8,
    rate_shock_bp: "100",
    spread_shock_bp: "0",
    assumption: "Illustrative parallel shock, not a forecast.",
  },
  {
    id: "monetary_easing",
    version: "stress-v1",
    name: "Monetary easing",
    event_subtype: "rate_cut",
    reference_impact: 8,
    rate_shock_bp: "-100",
    spread_shock_bp: "0",
    assumption: "Opposite illustrative shock.",
  },
];
export const run: Run = {
  id: "run1",
  status: "completed",
  event_id: "event1",
  signal_id: "signal1",
  mode: "automatic_simulation",
  created_at: "2026-10-05T00:00:00Z",
  scenario_id: "monetary_tightening",
  scenario_version: "stress-v1",
  portfolio_version: portfolio.version,
  actual_rate_shock_bp: "100",
  actual_spread_shock_bp: "0",
  impact_score: 8,
  base_total_usd: "1000000.00",
  stressed_total_usd: "960000.00",
  total_pnl_usd: "-40000.00",
  simulation_clock: signal.simulation_clock,
  override_reason: null,
  portfolio_snapshot: portfolio,
  scenario_snapshot: scenarios[0],
  signal_snapshot: signal,
  source_snapshot: [source],
  eligibility_snapshot: detail.eligibility,
  calculation_version: "linear-duration-v1",
  position_results: [
    {
      position_id: "L01",
      base_market_value_usd: "1000000.00",
      rate_applied: true,
      spread_applied: false,
      rate_pnl_usd: "-40000.00",
      spread_pnl_usd: "0.00",
      total_pnl_usd: "-40000.00",
      stressed_market_value_usd: "960000.00",
      explanation:
        "Cash rate-duration sensitivity; no matched corporate spread shock",
    },
  ],
};
export const health: Health = {
  status: "degraded",
  model_ready: true,
  portfolio_available: true,
  model_revision: "pinned-test-revision",
  model_error_code: null,
  sources: [
    {
      source_id: "fed_rss",
      stale: true,
      error_code: null,
      last_success_at: null,
      next_allowed_at: null,
    },
    {
      source_id: "fed_bluesky",
      stale: true,
      error_code: null,
      last_success_at: null,
      next_allowed_at: null,
    },
  ],
};
